# Generated by Django 5.0.6 on 2024-06-02 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="folder name"
                    ),
                ),
                ("folder_size", models.CharField(default=0, max_length=75)),
                (
                    "icon",
                    models.ImageField(
                        default="/static/icons/folder.png",
                        upload_to="",
                        verbose_name="folder icon",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_folders",
                        to="dropbox_app.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="file name"
                    ),
                ),
                (
                    "extension",
                    models.CharField(max_length=75, verbose_name="file extension"),
                ),
                ("data", models.FileField(upload_to="storage/", verbose_name="file")),
                ("file_size", models.CharField(max_length=75)),
                (
                    "icon",
                    models.ImageField(
                        default="/static/icons/document.png",
                        upload_to="",
                        verbose_name="file icon",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="dropbox_app.folder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(verbose_name="folder link")),
                (
                    "private",
                    models.BooleanField(
                        default=True, verbose_name="is link private or public"
                    ),
                ),
                (
                    "allowed_users",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder",
                        to="dropbox_app.folder",
                    ),
                ),
            ],
        ),
    ]
