# Generated by Django 5.0.6 on 2024-05-29 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="file name"
                    ),
                ),
                ("data", models.FileField(upload_to="", verbose_name="file")),
                ("file_size", models.CharField(max_length=75)),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="file share link"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="folder name"
                    ),
                ),
                ("folder_size", models.CharField(max_length=75)),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="file share link"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "files",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="dropbox_app.file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
