# Generated by Django 5.0.6 on 2024-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="data",
            field=models.FileField(
                upload_to="storage/% Y/% m/% d/", verbose_name="file"
            ),
        ),
    ]
