# Generated by Django 5.0.6 on 2024-06-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="private",
            field=models.BooleanField(verbose_name="is link private or public"),
        ),
    ]
