# Generated by Django 5.0.6 on 2024-05-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox_app", "0003_alter_file_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="folder_size",
            field=models.CharField(default=0, max_length=75),
        ),
    ]
