# Generated by Django 5.0.6 on 2024-05-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox_app", "0004_alter_folder_folder_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="files",
        ),
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="dropbox_app.folder",
            ),
        ),
    ]
