# Generated by Django 5.0.6 on 2024-05-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox_app", "0005_remove_folder_files_file_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="icon",
            field=models.ImageField(
                default="static/icons/document.png",
                upload_to="",
                verbose_name="file icon",
            ),
        ),
    ]
