# Generated by Django 5.0.6 on 2024-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox_app", "0006_file_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="icon",
            field=models.ImageField(
                default="static/icons/folder.png",
                upload_to="",
                verbose_name="folder icon",
            ),
        ),
    ]
