# Generated by Django 5.0.6 on 2024-05-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox_app", "0008_alter_file_icon_alter_folder_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="linked_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dropbox_app.folder",
            ),
        ),
    ]
