# Generated by Django 5.0.6 on 2024-05-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox_app", "0009_folder_linked_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="linked_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_folders",
                to="dropbox_app.folder",
            ),
        ),
    ]
