# Generated by Django 5.0.6 on 2024-05-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox_app", "0010_alter_folder_linked_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="extension",
            field=models.CharField(
                default=1, max_length=10, verbose_name="file extension"
            ),
            preserve_default=False,
        ),
    ]
