# Generated by Django 5.0.6 on 2024-05-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox_app", "0011_file_extension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="extension",
            field=models.CharField(max_length=75, verbose_name="file extension"),
        ),
    ]
